version: "3.3"
services:
  monitormail:
    image: mailhog/mailhog:latest
    container_name: monitormail
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
